// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vfyaxodigcwtbukaqfyz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZmeWF4b2RpZ2N3dGJ1a2FxZnl6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxODMxMjMsImV4cCI6MjA2ODc1OTEyM30.RpiaXcqvzHZnXAza4oy0RX4lBVIhJHR3NcR5Uj1bgPM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});